### ISSUE TITLE
Pager - unexpected hover

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/r4r-app#10]
### Issue description
This is not a show stopper. 
When you go from the 6th page in the results for cancer biology, then click on page 4 of the pager, the number 3 gets a hover state.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www-dev-acsf.cancer.gov/research/resources/search?from=100&researchAreas=cancer_biology
2. Go to 6th page of results 
3. Go to 4th page of results
4. See how 4 gets the active state and 3 gets hover (see attached)

### What's the expected result?
- Page 3 should not get the hover state treatment. Only page 4 should get the active state.

### What's the actual result?
- Page 4 gets the active state and page 3 gets the hover treatment.

### Additional details / screenshot
<img width="261" alt="Screen Shot 2020-08-06 at 10 17 24 AM" src="https://user-images.githubusercontent.com/4921685/89543309-c1a0d800-d7ce-11ea-9c83-ea55c2cfd85a.png">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
Confirmed that this issue no longer exists on Prod, so closing this ticket.
